Repository enisn/AutoFilterer, pull requests merged in 2020-11, with the labels that each got.

#14 Array Search Feature
  sandbox/WebApplication.API/Data/default.json
  src/AutoFilterer.Dynamics/AutoFilterer.Dynamics.csproj
  src/AutoFilterer.Swagger/AutoFilterer.Swagger.csproj
  src/AutoFilterer/Attributes/ArraySearchFilterAttribute.cs
  src/AutoFilterer/Attributes/CompareToAttribute.cs
  src/AutoFilterer/AutoFilterer.csproj
  tests/AutoFilterer.Tests/Attributes/ArraySearchAttributeTests.cs
  tests/AutoFilterer.Tests/Environment/Dtos/PreferencesFilter_ArraySearchWithAttribute.cs
  tests/AutoFilterer.Tests/Environment/Dtos/PreferencesFilter_ArraySearchWithoutAttribute.cs
Labels: documentation, feature, test

#15 ✨ Northwind Example Implementation to Sandbox
  .gitignore
  AutoFilterer.sln
  sandbox/WebApplication.API/Contexts/NorthwindDbContext.cs
  sandbox/WebApplication.API/Controllers/NorthwindController.cs
  sandbox/WebApplication.API/Dtos/Northwind/CategoryFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/CustomerCustomerDemoFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/CustomerDemographicFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/CustomerFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/EmployeeFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/OrderFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/ProductFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/RegionFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/ShipperFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/SupplierFilter.cs
  sandbox/WebApplication.API/Dtos/Northwind/TerritoryFilter.cs
  sandbox/WebApplication.API/Models/Northwind/Category.cs
  sandbox/WebApplication.API/Models/Northwind/Customer.cs
  sandbox/WebApplication.API/Models/Northwind/CustomerCustomerDemo.cs
  sandbox/WebApplication.API/Models/Northwind/CustomerDemographic.cs
  sandbox/WebApplication.API/Models/Northwind/Employee.cs
  sandbox/WebApplication.API/Models/Northwind/EmployeeTerritory.cs
  sandbox/WebApplication.API/Models/Northwind/Order.cs
  sandbox/WebApplication.API/Models/Northwind/OrderDetail.cs
  sandbox/WebApplication.API/Models/Northwind/OrderDetailsExtended.cs
  sandbox/WebApplication.API/Models/Northwind/Product.cs
  sandbox/WebApplication.API/Models/Northwind/Region.cs
  sandbox/WebApplication.API/Models/Northwind/Shipper.cs
  sandbox/WebApplication.API/Models/Northwind/Supplier.cs
  sandbox/WebApplication.API/Models/Northwind/Territory.cs
  sandbox/WebApplication.API/Properties/launchSettings.json
  sandbox/WebApplication.API/Startup.cs
  sandbox/WebApplication.API/WebApplication.API.csproj
  sandbox/WebApplication.API/WebApplication.API.xml
  sandbox/WebApplication.API/appsettings.json
  sandbox/WebApplication.API/efpt.config.json
Labels: documentation, enhancement

#16 ✨ Add LowerContains support for string fields.
  sandbox/WebApplication.API/Dtos/BookFilter.cs
  src/AutoFilterer/Attributes/ToLowerContainsComparisonAttribute.cs
  tests/AutoFilterer.Tests/Attributes/ToLowerContainsComparisonAttributeTests.cs
  tests/AutoFilterer.Tests/Environment/Dtos/BookFilter_LowerContains.cs
Labels: feature
